import type { CategoryId, Importance, KnowledgeItem } from "@/lib/types";

// Each KnowledgeItem is one examinable fact, written in original wording and
// mapped to the official handbook's knowledge areas. Facts are the unit the
// user masters; questions (see questions.ts) are interchangeable probes of them.

const ki = (
  id: string,
  categoryId: CategoryId,
  title: string,
  fact: string,
  entities: string[],
  importance: Importance = "medium",
): KnowledgeItem => ({
  id,
  categoryId,
  title,
  fact,
  entities,
  importance,
  status: "published",
});

export const knowledgeItems: KnowledgeItem[] = [
  // ── Values & Principles ───────────────────────────────────────────────
  ki(
    "fundamental-principles",
    "values",
    "Fundamental principles of British life",
    "The fundamental principles of British life include democracy, the rule of law, individual liberty, and tolerance of those with different faiths and beliefs.",
    ["democracy", "rule of law", "individual liberty", "tolerance"],
    "high",
  ),
  ki(
    "resident-responsibilities",
    "values",
    "Responsibilities of residents",
    "People who choose to live in the UK agree to respect and obey the law, respect the rights of others, treat others with fairness, and look after themselves, their family and the area they live in.",
    ["responsibilities", "rule of law"],
    "high",
  ),
  ki(
    "everyone-equal-under-law",
    "values",
    "Equality before the law",
    "In the UK, everyone is equal under the law, and no one is above it — including those who govern.",
    ["equality", "rule of law"],
    "high",
  ),
  ki(
    "tolerance-and-extremism",
    "values",
    "Tolerance, not extremism",
    "British society values tolerance of different faiths and beliefs, while extremism and intolerance are not accepted.",
    ["tolerance", "extremism"],
    "medium",
  ),
  ki(
    "test-requirement",
    "values",
    "Why the test exists",
    "Passing the Life in the UK Test is one of the requirements for applying for permanent residence (settlement) or British citizenship.",
    ["settlement", "citizenship", "Life in the UK Test"],
    "medium",
  ),
  ki(
    "english-language-requirement",
    "values",
    "Speaking English",
    "Applicants for settlement or citizenship are normally expected to be able to speak and read English to a required standard.",
    ["English language", "citizenship"],
    "medium",
  ),
  ki(
    "participation-community",
    "values",
    "Taking part in community life",
    "Taking part in community life — such as volunteering or helping neighbours — is seen as an important part of being a good citizen.",
    ["community", "volunteering"],
    "low",
  ),

  // ── What is the UK? ───────────────────────────────────────────────────
  ki(
    "uk-four-countries",
    "what-is-uk",
    "Countries of the UK",
    "The United Kingdom is made up of four countries: England, Scotland, Wales and Northern Ireland.",
    ["England", "Scotland", "Wales", "Northern Ireland"],
    "high",
  ),
  ki(
    "great-britain-definition",
    "what-is-uk",
    "Great Britain",
    "'Great Britain' refers to England, Scotland and Wales together — it does not include Northern Ireland.",
    ["Great Britain", "England", "Scotland", "Wales"],
    "high",
  ),
  ki(
    "union-flag-name",
    "what-is-uk",
    "The Union Flag",
    "The official flag of the UK is the Union Flag, commonly called the Union Jack, which combines the crosses of England, Scotland and Ireland.",
    ["Union Flag", "Union Jack"],
    "high",
  ),
  ki(
    "crown-dependencies",
    "what-is-uk",
    "Crown dependencies",
    "The Channel Islands and the Isle of Man are Crown dependencies — they are not part of the UK but are linked to it.",
    ["Channel Islands", "Isle of Man", "Crown dependencies"],
    "medium",
  ),
  ki(
    "capital-cities",
    "what-is-uk",
    "Capital cities",
    "The capital of the UK is London; the capital of Scotland is Edinburgh, of Wales is Cardiff, and of Northern Ireland is Belfast.",
    ["London", "Edinburgh", "Cardiff", "Belfast"],
    "high",
  ),
  ki(
    "overseas-territories",
    "what-is-uk",
    "Overseas territories",
    "There are several British overseas territories, such as St Helena and the Falkland Islands, which are also linked to the UK but not part of it.",
    ["overseas territories", "Falkland Islands"],
    "low",
  ),

  // ── UK History ────────────────────────────────────────────────────────
  ki(
    "magna-carta-1215",
    "history",
    "Magna Carta (1215)",
    "Magna Carta was signed by King John in 1215 and established the important idea that even the king was subject to the law.",
    ["Magna Carta", "King John", "1215"],
    "high",
  ),
  ki(
    "stonehenge-builders",
    "history",
    "Stonehenge",
    "Stonehenge, in Wiltshire, was built during the Stone Age and Bronze Age and is one of the most famous prehistoric monuments in the world.",
    ["Stonehenge", "Wiltshire"],
    "medium",
  ),
  ki(
    "1066-norman-conquest",
    "history",
    "Norman Conquest (1066)",
    "In 1066 William the Conqueror defeated the English at the Battle of Hastings — the last successful foreign invasion of England.",
    ["William the Conqueror", "Battle of Hastings", "1066"],
    "high",
  ),
  ki(
    "black-death",
    "history",
    "The Black Death",
    "The Black Death was a plague that arrived in Britain in 1348 and killed a large part of the population.",
    ["Black Death", "plague", "1348"],
    "medium",
  ),
  ki(
    "henry-viii-church",
    "history",
    "Henry VIII and the Church",
    "Henry VIII broke away from the Church of Rome and established the Church of England so that he could divorce and remarry.",
    ["Henry VIII", "Church of England", "Reformation"],
    "high",
  ),
  ki(
    "elizabeth-i-armada",
    "history",
    "Elizabeth I and the Armada",
    "During the reign of Elizabeth I, the English navy defeated the Spanish Armada in 1588.",
    ["Elizabeth I", "Spanish Armada", "1588"],
    "medium",
  ),
  ki(
    "gunpowder-plot-1605",
    "history",
    "The Gunpowder Plot (1605)",
    "In 1605 Guy Fawkes and other conspirators tried and failed to blow up Parliament — an event still marked on 5 November.",
    ["Guy Fawkes", "Gunpowder Plot", "1605"],
    "medium",
  ),
  ki(
    "civil-war-1642",
    "history",
    "The English Civil War",
    "The English Civil War between the King and Parliament began in 1642 and led to the execution of King Charles I in 1649.",
    ["Civil War", "Charles I", "Oliver Cromwell"],
    "medium",
  ),
  ki(
    "great-fire-1666",
    "history",
    "The Great Fire of London (1666)",
    "The Great Fire of London in 1666 destroyed much of the city, including the original St Paul's Cathedral.",
    ["Great Fire of London", "1666", "St Paul's"],
    "low",
  ),
  ki(
    "act-of-union-1707",
    "history",
    "Act of Union (1707)",
    "The Act of Union of 1707 joined England and Scotland to create the Kingdom of Great Britain with a single parliament.",
    ["Act of Union", "1707", "Great Britain"],
    "medium",
  ),
  ki(
    "industrial-revolution",
    "history",
    "The Industrial Revolution",
    "The Industrial Revolution, which made Britain the first industrial nation, saw the rapid growth of factories, mines and railways in the 18th and 19th centuries.",
    ["Industrial Revolution", "factories", "railways"],
    "medium",
  ),
  ki(
    "battle-of-trafalgar",
    "history",
    "Battle of Trafalgar (1805)",
    "Admiral Nelson led the British navy to victory over the French and Spanish at the Battle of Trafalgar in 1805; his ship was HMS Victory.",
    ["Nelson", "Trafalgar", "HMS Victory", "1805"],
    "medium",
  ),
  ki(
    "world-war-one",
    "history",
    "First World War",
    "The First World War began in 1914 and ended in 1918, with the Allies defeating the Central Powers.",
    ["First World War", "1914", "1918"],
    "medium",
  ),
  ki(
    "world-war-two-churchill",
    "history",
    "Churchill and the Second World War",
    "Winston Churchill was Prime Minister for most of the Second World War and led Britain to victory; the war in Europe ended in 1945.",
    ["Winston Churchill", "Second World War", "1945"],
    "high",
  ),
  ki(
    "votes-for-women",
    "history",
    "Votes for women",
    "The suffragettes campaigned for women's right to vote; women over 30 were first given the vote in 1918, and equal voting rights with men followed in 1928.",
    ["suffragettes", "Emmeline Pankhurst", "1928"],
    "medium",
  ),

  // ── Modern Society ────────────────────────────────────────────────────
  ki(
    "uk-population-growth",
    "modern-society",
    "A growing population",
    "The UK population has grown over time and is now more than 60 million people, with growth driven partly by migration.",
    ["population", "migration"],
    "low",
  ),
  ki(
    "official-languages-other",
    "modern-society",
    "Languages of the UK",
    "Besides English, other languages such as Welsh, Scottish Gaelic and Irish Gaelic are spoken in parts of the UK.",
    ["Welsh", "Gaelic"],
    "low",
  ),
  ki(
    "christianity-largest-religion",
    "modern-society",
    "Religion in the UK",
    "The UK is historically a Christian country, but it is a diverse society where people follow many religions or none.",
    ["Christianity", "religion", "diversity"],
    "medium",
  ),
  ki(
    "church-of-england-established",
    "modern-society",
    "The established church",
    "The Church of England is the established church in England, and its head is the monarch.",
    ["Church of England", "monarch"],
    "medium",
  ),
  ki(
    "patron-saints-days",
    "modern-society",
    "Patron saints' days",
    "Each UK nation has a patron saint's day: St David's Day (1 March), St Patrick's Day (17 March), St George's Day (23 April) and St Andrew's Day (30 November).",
    ["patron saints", "saints' days"],
    "high",
  ),
  ki(
    "currency-pound",
    "modern-society",
    "The currency",
    "The currency of the UK is the pound sterling (£), divided into 100 pence.",
    ["pound sterling", "currency"],
    "medium",
  ),

  // ── Government & Democracy ────────────────────────────────────────────
  ki(
    "constitutional-monarchy",
    "government",
    "Constitutional monarchy",
    "The UK is a constitutional monarchy: the monarch is head of state but does not make political decisions, which are made by an elected government.",
    ["constitutional monarchy", "monarch", "head of state"],
    "high",
  ),
  ki(
    "parliament-two-houses",
    "government",
    "Houses of Parliament",
    "Parliament is made up of two chambers: the House of Commons and the House of Lords.",
    ["House of Commons", "House of Lords", "Parliament"],
    "high",
  ),
  ki(
    "mps-elected",
    "government",
    "MPs and elections",
    "Members of Parliament (MPs) in the House of Commons are elected by the public, with each MP representing a constituency.",
    ["MPs", "constituency", "House of Commons"],
    "high",
  ),
  ki(
    "general-election-frequency",
    "government",
    "General elections",
    "A general election to choose all MPs is normally held at least every five years.",
    ["general election", "five years"],
    "high",
  ),
  ki(
    "prime-minister-role",
    "government",
    "The Prime Minister",
    "The Prime Minister is the leader of the government, normally the leader of the political party that wins the most seats in a general election.",
    ["Prime Minister", "government"],
    "high",
  ),
  ki(
    "downing-street-10",
    "government",
    "10 Downing Street",
    "The Prime Minister lives and works at 10 Downing Street in London and appoints the senior ministers known as the Cabinet.",
    ["10 Downing Street", "Cabinet"],
    "medium",
  ),
  ki(
    "voting-age-18",
    "government",
    "Voting age",
    "You can vote in a general election once you are 18 years old and registered to vote.",
    ["voting age", "18"],
    "high",
  ),
  ki(
    "devolved-administrations",
    "government",
    "Devolved governments",
    "Some powers are devolved to the Scottish Parliament, the Welsh Parliament (Senedd) and the Northern Ireland Assembly.",
    ["devolution", "Senedd", "Scottish Parliament"],
    "medium",
  ),
  ki(
    "speaker-of-commons",
    "government",
    "The Speaker",
    "The Speaker keeps order during debates in the House of Commons and is politically neutral.",
    ["Speaker", "House of Commons"],
    "low",
  ),
  ki(
    "civil-service-neutral",
    "government",
    "The civil service",
    "Civil servants are politically neutral and carry out government policy whichever party is in power.",
    ["civil service", "neutral"],
    "low",
  ),

  // ── Law & Justice ─────────────────────────────────────────────────────
  ki(
    "police-protect-public",
    "law-justice",
    "Role of the police",
    "The job of the police is to protect life and property, prevent and detect crime, and keep the peace; they must themselves obey the law.",
    ["police", "law"],
    "high",
  ),
  ki(
    "judiciary-independent",
    "law-justice",
    "An independent judiciary",
    "Judges are independent of the government, and their role is to interpret and apply the law fairly.",
    ["judges", "judiciary", "independence"],
    "high",
  ),
  ki(
    "criminal-vs-civil-law",
    "law-justice",
    "Criminal and civil law",
    "Criminal law deals with crimes such as theft and assault, while civil law settles disputes between people or organisations.",
    ["criminal law", "civil law"],
    "medium",
  ),
  ki(
    "jury-system",
    "law-justice",
    "Trial by jury",
    "In serious criminal cases a jury of members of the public decides whether the accused is guilty or not guilty.",
    ["jury", "trial"],
    "medium",
  ),
  ki(
    "legal-aid",
    "law-justice",
    "Legal advice",
    "People who need legal help but cannot afford it may be able to get free or low-cost advice, and in some cases legal aid.",
    ["legal aid", "advice"],
    "low",
  ),
  ki(
    "police-and-crime-commissioners",
    "law-justice",
    "Police and Crime Commissioners",
    "In England and Wales, Police and Crime Commissioners are elected by the public to oversee how local areas are policed.",
    ["Police and Crime Commissioners", "elections"],
    "low",
  ),

  // ── Rights & Responsibilities ─────────────────────────────────────────
  ki(
    "right-to-vote",
    "rights-responsibilities",
    "The right to vote",
    "British citizens and some others have the right to vote in elections, and registering to vote is a civic responsibility.",
    ["voting", "rights"],
    "medium",
  ),
  ki(
    "jury-duty-responsibility",
    "rights-responsibilities",
    "Jury service",
    "Serving on a jury when called is one of the responsibilities of people aged 18 or over who are registered to vote.",
    ["jury service", "responsibility"],
    "medium",
  ),
  ki(
    "paying-tax",
    "rights-responsibilities",
    "Paying tax",
    "People in the UK pay tax on their income and on many goods and services, which funds public services such as the NHS.",
    ["tax", "income tax", "NHS"],
    "medium",
  ),
  ki(
    "national-insurance",
    "rights-responsibilities",
    "National Insurance",
    "Most workers pay National Insurance contributions, which help to pay for benefits and the State Pension.",
    ["National Insurance", "State Pension"],
    "low",
  ),
  ki(
    "nhs-free-at-point-of-use",
    "rights-responsibilities",
    "The NHS",
    "The National Health Service (NHS) provides healthcare that is mostly free at the point of use for residents of the UK.",
    ["NHS", "healthcare"],
    "medium",
  ),
  ki(
    "respecting-environment",
    "rights-responsibilities",
    "Caring for the environment",
    "Looking after the environment — for example by recycling and not dropping litter — is a responsibility shared by everyone.",
    ["environment", "recycling"],
    "low",
  ),

  // ── Culture & Traditions ──────────────────────────────────────────────
  ki(
    "christmas-day",
    "culture-traditions",
    "Christmas Day",
    "Christmas Day, on 25 December, is celebrated by Christians as the birth of Jesus Christ and is a public holiday.",
    ["Christmas", "25 December"],
    "medium",
  ),
  ki(
    "easter-tradition",
    "culture-traditions",
    "Easter",
    "Easter, in March or April, marks the death and resurrection of Jesus Christ; Good Friday and Easter Monday are public holidays.",
    ["Easter", "Good Friday"],
    "medium",
  ),
  ki(
    "bonfire-night",
    "culture-traditions",
    "Bonfire Night",
    "Bonfire Night, on 5 November, marks the failure of the Gunpowder Plot of 1605 with fireworks and bonfires.",
    ["Bonfire Night", "Guy Fawkes", "5 November"],
    "medium",
  ),
  ki(
    "remembrance-day",
    "culture-traditions",
    "Remembrance Day",
    "Remembrance Day, on 11 November, honours those who died in wars; people wear poppies to remember them.",
    ["Remembrance Day", "poppy", "11 November"],
    "high",
  ),
  ki(
    "diwali-celebration",
    "culture-traditions",
    "Diwali",
    "Diwali, the festival of lights, is celebrated by Hindus and Sikhs in the autumn.",
    ["Diwali", "Hindus", "Sikhs"],
    "low",
  ),
  ki(
    "hogmanay-scotland",
    "culture-traditions",
    "Hogmanay",
    "Hogmanay is the Scottish celebration of New Year's Eve, marked with lively festivities.",
    ["Hogmanay", "Scotland", "New Year"],
    "low",
  ),
  ki(
    "bank-holidays",
    "culture-traditions",
    "Bank holidays",
    "Bank holidays are public holidays during the year when most businesses and many shops are closed.",
    ["bank holidays", "public holidays"],
    "low",
  ),

  // ── Geography & Symbols ───────────────────────────────────────────────
  ki(
    "st-george-england",
    "geography-symbols",
    "Patron saint of England",
    "St George is the patron saint of England, and his cross — a red cross on a white background — is the English flag.",
    ["St George", "England"],
    "high",
  ),
  ki(
    "st-andrew-scotland",
    "geography-symbols",
    "Patron saint of Scotland",
    "St Andrew is the patron saint of Scotland, and the Scottish flag is a white diagonal cross on a blue background.",
    ["St Andrew", "Scotland"],
    "high",
  ),
  ki(
    "st-david-wales",
    "geography-symbols",
    "Patron saint of Wales",
    "St David is the patron saint of Wales, celebrated on 1 March.",
    ["St David", "Wales"],
    "high",
  ),
  ki(
    "st-patrick-northern-ireland",
    "geography-symbols",
    "Patron saint of Northern Ireland",
    "St Patrick is the patron saint of Northern Ireland, celebrated on 17 March.",
    ["St Patrick", "Northern Ireland"],
    "high",
  ),
  ki(
    "ben-nevis-highest",
    "geography-symbols",
    "Ben Nevis",
    "Ben Nevis, in Scotland, is the highest mountain in the United Kingdom.",
    ["Ben Nevis", "Scotland", "mountain"],
    "medium",
  ),
  ki(
    "national-flowers",
    "geography-symbols",
    "National flowers",
    "The rose is the national flower of England, the thistle of Scotland, the daffodil of Wales and the shamrock of Northern Ireland.",
    ["rose", "thistle", "daffodil", "shamrock"],
    "medium",
  ),
  ki(
    "big-ben-clock",
    "geography-symbols",
    "Big Ben",
    "'Big Ben' is the nickname of the great bell in the clock tower at the Houses of Parliament in London.",
    ["Big Ben", "Parliament", "London"],
    "low",
  ),
  ki(
    "lake-district",
    "geography-symbols",
    "The Lake District",
    "The Lake District in north-west England is the UK's largest national park and is famous for its lakes and mountains.",
    ["Lake District", "national park"],
    "low",
  ),

  // ── Sport, Arts & Science ─────────────────────────────────────────────
  ki(
    "bannister-four-minute-mile",
    "sport-arts-science",
    "Roger Bannister",
    "Sir Roger Bannister was the first person to run a mile in under four minutes, achieving this in 1954.",
    ["Roger Bannister", "athletics", "1954"],
    "high",
  ),
  ki(
    "shakespeare-playwright",
    "sport-arts-science",
    "William Shakespeare",
    "William Shakespeare was a playwright and poet from Stratford-upon-Avon, famous for plays such as Hamlet and Romeo and Juliet.",
    ["Shakespeare", "Stratford-upon-Avon", "playwright"],
    "high",
  ),
  ki(
    "newton-gravity",
    "sport-arts-science",
    "Isaac Newton",
    "Sir Isaac Newton was a scientist famous for his work on gravity and the laws of motion.",
    ["Isaac Newton", "gravity", "science"],
    "high",
  ),
  ki(
    "darwin-evolution",
    "sport-arts-science",
    "Charles Darwin",
    "Charles Darwin developed the theory of evolution and wrote 'On the Origin of Species'.",
    ["Charles Darwin", "evolution"],
    "high",
  ),
  ki(
    "fleming-penicillin",
    "sport-arts-science",
    "Alexander Fleming",
    "Sir Alexander Fleming, a Scottish scientist, discovered penicillin, the first widely used antibiotic.",
    ["Alexander Fleming", "penicillin"],
    "medium",
  ),
  ki(
    "turing-computing",
    "sport-arts-science",
    "Alan Turing",
    "Alan Turing was a mathematician who helped break enemy codes in the Second World War and is seen as a founder of modern computing.",
    ["Alan Turing", "computing", "codebreaking"],
    "medium",
  ),
  ki(
    "football-origins",
    "sport-arts-science",
    "Football",
    "Football is the UK's most popular sport, and the first professional football clubs were formed in Britain in the 19th century.",
    ["football", "sport"],
    "medium",
  ),
  ki(
    "wimbledon-tennis",
    "sport-arts-science",
    "Wimbledon",
    "Wimbledon is the oldest tennis tournament in the world and is held in London each year.",
    ["Wimbledon", "tennis", "London"],
    "medium",
  ),
  ki(
    "the-beatles",
    "sport-arts-science",
    "The Beatles",
    "The Beatles, from Liverpool, were one of the most influential pop groups of the 1960s.",
    ["The Beatles", "Liverpool", "music"],
    "low",
  ),
  ki(
    "turner-painter",
    "sport-arts-science",
    "JMW Turner",
    "JMW Turner was an influential British landscape painter, and the prestigious Turner Prize for art is named after him.",
    ["Turner", "Turner Prize", "art"],
    "low",
  ),

  // ── Additional facts (broader coverage) ───────────────────────────────
  ki(
    "romans-in-britain",
    "history",
    "The Romans in Britain",
    "The Romans ruled Britain for about 400 years and built roads, towns and defences such as Hadrian's Wall.",
    ["Romans", "Hadrian's Wall"],
    "medium",
  ),
  ki(
    "boudicca-revolt",
    "history",
    "Boudicca",
    "Boudicca was a queen of a British tribe who led a revolt against the Roman army and is remembered as an early British heroine.",
    ["Boudicca", "Romans"],
    "low",
  ),
  ki(
    "florence-nightingale",
    "history",
    "Florence Nightingale",
    "Florence Nightingale is regarded as the founder of modern nursing for her work caring for soldiers in the Crimean War.",
    ["Florence Nightingale", "nursing"],
    "medium",
  ),
  ki(
    "abolition-slave-trade",
    "history",
    "Abolition of the slave trade",
    "The slave trade was made illegal across the British Empire in 1807, and William Wilberforce was a leading campaigner against it.",
    ["slavery", "William Wilberforce", "1807"],
    "medium",
  ),
  ki(
    "nhs-founded-1948",
    "history",
    "Founding of the NHS",
    "The National Health Service was founded in 1948 to provide healthcare for everyone, led by the minister Aneurin Bevan.",
    ["NHS", "1948", "Aneurin Bevan"],
    "high",
  ),
  ki(
    "queen-elizabeth-ii-reign",
    "modern-society",
    "Queen Elizabeth II",
    "Queen Elizabeth II reigned from 1952 and became the longest-reigning monarch in British history before her death in 2022.",
    ["Elizabeth II", "monarch"],
    "medium",
  ),
  ki(
    "commonwealth-association",
    "government",
    "The Commonwealth",
    "The Commonwealth is an association of countries, most of which were once part of the British Empire, that work together on shared goals.",
    ["Commonwealth", "British Empire"],
    "medium",
  ),
  ki(
    "house-of-lords-unelected",
    "government",
    "The House of Lords",
    "Members of the House of Lords are not elected by the public; they review and suggest changes to laws proposed by the House of Commons.",
    ["House of Lords", "peers"],
    "medium",
  ),
  ki(
    "secret-ballot",
    "government",
    "The secret ballot",
    "In UK elections people vote in secret, so no one can be forced to reveal how they voted.",
    ["secret ballot", "elections"],
    "medium",
  ),
  ki(
    "magistrates-courts",
    "law-justice",
    "Magistrates",
    "Most minor criminal cases in England and Wales are heard by magistrates, who are usually unpaid volunteers from the local community.",
    ["magistrates", "courts"],
    "low",
  ),
  ki(
    "human-rights-equality",
    "rights-responsibilities",
    "Equality and discrimination",
    "It is against the law to discriminate against someone because of characteristics such as sex, race, religion, age or disability.",
    ["equality", "discrimination"],
    "high",
  ),
  ki(
    "freedom-of-speech",
    "rights-responsibilities",
    "Freedom of speech",
    "People in the UK have the right to freedom of speech, as long as it is within the law and does not harm or incite hatred against others.",
    ["freedom of speech", "rights"],
    "medium",
  ),
  ki(
    "valentines-day",
    "culture-traditions",
    "Valentine's Day",
    "St Valentine's Day, on 14 February, is when people who are in love send cards and gifts to one another.",
    ["Valentine's Day", "14 February"],
    "low",
  ),
  ki(
    "mothering-sunday",
    "culture-traditions",
    "Mother's Day",
    "Mothering Sunday, or Mother's Day, is the Sunday three weeks before Easter, when people thank their mothers.",
    ["Mother's Day", "Easter"],
    "low",
  ),
  ki(
    "edinburgh-festival",
    "culture-traditions",
    "The Edinburgh Festival",
    "The Edinburgh Festival is a series of arts and culture events held in Scotland's capital each summer, famous for its Fringe.",
    ["Edinburgh Festival", "Fringe"],
    "low",
  ),
  ki(
    "severn-longest-river",
    "geography-symbols",
    "The River Severn",
    "The River Severn is the longest river in the United Kingdom.",
    ["River Severn", "rivers"],
    "low",
  ),
  ki(
    "snowdon-wales",
    "geography-symbols",
    "Snowdon",
    "Snowdon, in Wales, is the highest mountain in Wales and gives its name to the Snowdonia national park.",
    ["Snowdon", "Wales", "Snowdonia"],
    "low",
  ),
  ki(
    "dickens-novelist",
    "sport-arts-science",
    "Charles Dickens",
    "Charles Dickens was a famous 19th-century novelist whose works include 'Oliver Twist' and 'A Christmas Carol'.",
    ["Charles Dickens", "novels"],
    "medium",
  ),
];

export const knowledgeItemById = new Map(knowledgeItems.map((k) => [k.id, k]));
