import type { Difficulty, Question } from "@/lib/types";
import { knowledgeItemById } from "./knowledge-items";

// Original practice questions (no official wording is reproduced). Each question
// is a *variant* probing one or more KnowledgeItems, so the user masters the
// fact rather than a memorised answer position. Category is inferred from the
// first linked fact to keep content self-consistent. The correct answer is
// authored first (option "-a"); the quiz runner shuffles options at display.

const q = (
  id: string,
  knowledgeItemIds: string[],
  prompt: string,
  correct: string,
  distractors: [string, string, string],
  explanation: string,
  difficulty: Difficulty = "medium",
): Question => {
  const first = knowledgeItemById.get(knowledgeItemIds[0]);
  if (!first) throw new Error(`Question ${id} references unknown knowledge item`);
  return {
    id,
    prompt,
    options: [
      { id: `${id}-a`, text: correct },
      { id: `${id}-b`, text: distractors[0] },
      { id: `${id}-c`, text: distractors[1] },
      { id: `${id}-d`, text: distractors[2] },
    ],
    correctOptionIds: [`${id}-a`],
    explanation,
    categoryId: first.categoryId,
    knowledgeItemIds,
    difficulty,
    status: "published",
  };
};

export const questions: Question[] = [
  // ── Values & Principles ───────────────────────────────────────────────
  q(
    "q-values-1",
    ["fundamental-principles"],
    "Which of these is a fundamental principle of British life?",
    "The rule of law",
    [
      "Compulsory military service",
      "A single state religion for all",
      "State control of the press",
    ],
    "Democracy, the rule of law, individual liberty and tolerance are fundamental principles of British life.",
    "easy",
  ),
  q(
    "q-values-2",
    ["fundamental-principles"],
    "Tolerance of those with different faiths and beliefs is best described as:",
    "A fundamental principle of British life",
    [
      "A recent legal requirement only",
      "Something expected only of citizens",
      "An optional cultural preference",
    ],
    "Tolerance of different faiths and beliefs is one of the UK's fundamental principles.",
  ),
  q(
    "q-values-3",
    ["everyone-equal-under-law"],
    "Under British law, who is subject to the law?",
    "Everyone, including those who govern",
    [
      "Only ordinary citizens",
      "Everyone except senior judges",
      "Everyone except the monarch",
    ],
    "Everyone is equal under the law and no one is above it, including those in power.",
  ),
  q(
    "q-values-4",
    ["resident-responsibilities"],
    "Which of these is a responsibility that people in the UK agree to accept?",
    "To respect and obey the law",
    [
      "To join a political party",
      "To attend church weekly",
      "To vote for the governing party",
    ],
    "Residents agree to obey the law, respect others' rights and treat people fairly.",
    "easy",
  ),
  q(
    "q-values-5",
    ["test-requirement"],
    "Passing the Life in the UK Test is a requirement for:",
    "Applying for settlement or British citizenship",
    ["Getting a UK driving licence", "Opening a UK bank account", "Registering with a GP"],
    "The test is part of the requirements for settlement (permanent residence) or citizenship.",
  ),
  q(
    "q-values-6",
    ["participation-community"],
    "Helping neighbours and volunteering are examples of:",
    "Taking part in community life",
    [
      "A legal obligation for residents",
      "Requirements to renew a visa",
      "Ways to avoid paying tax",
    ],
    "Taking part in community life is regarded as an important part of being a good citizen.",
  ),

  // ── What is the UK? ───────────────────────────────────────────────────
  q(
    "q-uk-1",
    ["uk-four-countries"],
    "How many countries make up the United Kingdom?",
    "Four",
    ["Three", "Two", "Five"],
    "The UK is made up of England, Scotland, Wales and Northern Ireland.",
    "easy",
  ),
  q(
    "q-uk-2",
    ["uk-four-countries"],
    "Which of these is one of the four countries of the UK?",
    "Northern Ireland",
    ["The Republic of Ireland", "The Isle of Man", "Jersey"],
    "Northern Ireland is part of the UK; the Republic of Ireland is a separate country.",
  ),
  q(
    "q-uk-3",
    ["great-britain-definition"],
    "'Great Britain' refers to which three countries?",
    "England, Scotland and Wales",
    [
      "England, Wales and Northern Ireland",
      "England, Scotland and Ireland",
      "Scotland, Wales and Northern Ireland",
    ],
    "Great Britain means England, Scotland and Wales — it does not include Northern Ireland.",
  ),
  q(
    "q-uk-4",
    ["union-flag-name"],
    "What is the official flag of the United Kingdom called?",
    "The Union Flag (Union Jack)",
    ["The St George's Cross", "The Royal Standard", "The Commonwealth Flag"],
    "The UK flag is the Union Flag, often called the Union Jack.",
    "easy",
  ),
  q(
    "q-uk-5",
    ["crown-dependencies"],
    "The Isle of Man and the Channel Islands are:",
    "Crown dependencies, not part of the UK",
    ["Counties of England", "Part of Great Britain", "British overseas territories"],
    "They are Crown dependencies — linked to the UK but not part of it.",
  ),
  q(
    "q-uk-6",
    ["capital-cities"],
    "What is the capital city of Scotland?",
    "Edinburgh",
    ["Glasgow", "Aberdeen", "Dundee"],
    "Edinburgh is the capital of Scotland; Glasgow is its largest city.",
    "easy",
  ),
  q(
    "q-uk-7",
    ["capital-cities"],
    "What is the capital city of Wales?",
    "Cardiff",
    ["Swansea", "Newport", "Bangor"],
    "Cardiff is the capital of Wales.",
    "easy",
  ),
  q(
    "q-uk-8",
    ["capital-cities"],
    "Belfast is the capital city of which part of the UK?",
    "Northern Ireland",
    ["Scotland", "Wales", "The Republic of Ireland"],
    "Belfast is the capital of Northern Ireland.",
  ),

  // ── UK History ────────────────────────────────────────────────────────
  q(
    "q-history-1",
    ["magna-carta-1215"],
    "What important principle did Magna Carta establish in 1215?",
    "That even the king was subject to the law",
    [
      "That women could vote",
      "That Parliament could be dissolved",
      "That England and Scotland were united",
    ],
    "Magna Carta, signed by King John in 1215, established that the king too must obey the law.",
  ),
  q(
    "q-history-2",
    ["magna-carta-1215"],
    "Magna Carta was signed by which king?",
    "King John",
    ["King Henry VIII", "King Charles I", "King William the Conqueror"],
    "King John signed Magna Carta in 1215.",
  ),
  q(
    "q-history-3",
    ["1066-norman-conquest"],
    "Who defeated the English at the Battle of Hastings in 1066?",
    "William the Conqueror",
    ["Julius Caesar", "Oliver Cromwell", "Alfred the Great"],
    "William the Conqueror's victory in 1066 was the last successful foreign invasion of England.",
  ),
  q(
    "q-history-4",
    ["1066-norman-conquest"],
    "The year 1066 is associated with which event?",
    "The Norman Conquest of England",
    ["The signing of Magna Carta", "The Great Fire of London", "The Spanish Armada"],
    "1066 marks the Norman Conquest, when William the Conqueror won the Battle of Hastings.",
  ),
  q(
    "q-history-5",
    ["henry-viii-church"],
    "Why did Henry VIII establish the Church of England?",
    "So that he could divorce and remarry",
    [
      "To unite England and Scotland",
      "To end the Civil War",
      "To defeat the Spanish Armada",
    ],
    "Henry VIII broke from the Church of Rome and set up the Church of England, allowing him to divorce.",
  ),
  q(
    "q-history-6",
    ["elizabeth-i-armada"],
    "During whose reign did England defeat the Spanish Armada in 1588?",
    "Elizabeth I",
    ["Queen Victoria", "Mary I", "Anne"],
    "The Spanish Armada was defeated in 1588, during the reign of Elizabeth I.",
  ),
  q(
    "q-history-7",
    ["gunpowder-plot-1605"],
    "Who is associated with the failed Gunpowder Plot of 1605?",
    "Guy Fawkes",
    ["Oliver Cromwell", "Horatio Nelson", "Isambard Kingdom Brunel"],
    "Guy Fawkes and others tried to blow up Parliament in 1605, an event marked on 5 November.",
  ),
  q(
    "q-history-8",
    ["civil-war-1642"],
    "The English Civil War was a conflict between the King and:",
    "Parliament",
    ["The Church of Rome", "Scotland", "France"],
    "The Civil War from 1642 was between the King and Parliament, and led to Charles I's execution.",
  ),
  q(
    "q-history-9",
    ["act-of-union-1707"],
    "The Act of Union of 1707 joined which two countries under one parliament?",
    "England and Scotland",
    ["England and Wales", "England and Ireland", "Scotland and Ireland"],
    "The 1707 Act of Union created the Kingdom of Great Britain from England and Scotland.",
  ),
  q(
    "q-history-10",
    ["industrial-revolution"],
    "Britain is known as the first country to undergo which transformation?",
    "The Industrial Revolution",
    ["The Renaissance", "The Reformation", "The Norman Conquest"],
    "The Industrial Revolution made Britain the first industrial nation.",
  ),
  q(
    "q-history-11",
    ["battle-of-trafalgar"],
    "Which admiral led the British navy to victory at the Battle of Trafalgar in 1805?",
    "Admiral Nelson",
    ["The Duke of Wellington", "Sir Francis Drake", "Admiral Beatty"],
    "Admiral Nelson won at Trafalgar in 1805 aboard HMS Victory.",
  ),
  q(
    "q-history-12",
    ["world-war-two-churchill"],
    "Who was Prime Minister for most of the Second World War?",
    "Winston Churchill",
    ["Clement Attlee", "Neville Chamberlain", "David Lloyd George"],
    "Winston Churchill led Britain through most of the Second World War.",
  ),
  q(
    "q-history-13",
    ["world-war-two-churchill"],
    "In which year did the Second World War end in Europe?",
    "1945",
    ["1918", "1939", "1950"],
    "The war in Europe ended in 1945.",
  ),
  q(
    "q-history-14",
    ["votes-for-women"],
    "What did the suffragettes campaign for?",
    "The right of women to vote",
    ["Free healthcare", "An end to the monarchy", "Shorter working hours"],
    "The suffragettes campaigned for women's right to vote; equal voting rights came in 1928.",
  ),
  q(
    "q-history-15",
    ["world-war-one"],
    "In which year did the First World War begin?",
    "1914",
    ["1905", "1918", "1939"],
    "The First World War began in 1914 and ended in 1918.",
  ),
  q(
    "q-history-16",
    ["black-death"],
    "The Black Death that reached Britain in 1348 was a:",
    "Plague that killed a large part of the population",
    ["Great fire", "Foreign invasion", "Severe famine caused by drought"],
    "The Black Death was a plague that killed a significant proportion of the population.",
  ),

  // ── Modern Society ────────────────────────────────────────────────────
  q(
    "q-society-1",
    ["patron-saints-days"],
    "On what date is St George's Day celebrated?",
    "23 April",
    ["1 March", "17 March", "30 November"],
    "St George's Day, for England, is 23 April.",
  ),
  q(
    "q-society-2",
    ["patron-saints-days"],
    "Which patron saint's day falls on 1 March?",
    "St David's Day",
    ["St Patrick's Day", "St George's Day", "St Andrew's Day"],
    "St David's Day (Wales) is celebrated on 1 March.",
  ),
  q(
    "q-society-3",
    ["currency-pound"],
    "What is the currency of the UK?",
    "The pound sterling",
    ["The euro", "The dollar", "The crown"],
    "The UK currency is the pound sterling (£), divided into 100 pence.",
    "easy",
  ),
  q(
    "q-society-4",
    ["church-of-england-established"],
    "Who is the head of the Church of England?",
    "The monarch",
    ["The Prime Minister", "The Pope", "The Archbishop of Canterbury alone"],
    "The Church of England is the established church and the monarch is its head.",
  ),
  q(
    "q-society-5",
    ["christianity-largest-religion"],
    "Which statement best describes religion in the UK today?",
    "It is historically Christian but religiously diverse",
    [
      "Everyone must follow one official religion",
      "Religion is banned in public life",
      "No religions are practised",
    ],
    "The UK is historically Christian but a diverse society where people follow many faiths or none.",
  ),
  q(
    "q-society-6",
    ["official-languages-other"],
    "Besides English, which language is widely spoken in parts of the UK?",
    "Welsh",
    ["Dutch", "Latin", "Portuguese"],
    "Welsh, Scottish Gaelic and Irish Gaelic are spoken in parts of the UK.",
  ),

  // ── Government & Democracy ────────────────────────────────────────────
  q(
    "q-gov-1",
    ["constitutional-monarchy"],
    "What kind of system of government does the UK have?",
    "A constitutional monarchy",
    ["An absolute monarchy", "A military dictatorship", "A one-party state"],
    "The UK is a constitutional monarchy: the monarch is head of state but does not run the government.",
  ),
  q(
    "q-gov-2",
    ["parliament-two-houses"],
    "What are the two chambers of Parliament called?",
    "The House of Commons and the House of Lords",
    [
      "The Senate and the Congress",
      "The Upper and Lower Courts",
      "The Cabinet and the Assembly",
    ],
    "Parliament has two Houses: the Commons and the Lords.",
    "easy",
  ),
  q(
    "q-gov-3",
    ["mps-elected"],
    "What is the area represented by a Member of Parliament called?",
    "A constituency",
    ["A county", "A parish", "A ward"],
    "Each MP represents a constituency.",
  ),
  q(
    "q-gov-4",
    ["general-election-frequency"],
    "At least how often must a general election normally be held?",
    "Every five years",
    ["Every two years", "Every ten years", "Every year"],
    "A general election is normally held at least every five years.",
  ),
  q(
    "q-gov-5",
    ["prime-minister-role"],
    "Who is normally appointed as Prime Minister after a general election?",
    "The leader of the party that wins the most seats",
    [
      "The longest-serving MP",
      "The leader of the House of Lords",
      "The monarch's eldest child",
    ],
    "The Prime Minister is usually the leader of the party with the most seats in the Commons.",
  ),
  q(
    "q-gov-6",
    ["downing-street-10"],
    "Where does the Prime Minister live and work?",
    "10 Downing Street",
    ["Buckingham Palace", "The Tower of London", "Windsor Castle"],
    "The Prime Minister's official residence is 10 Downing Street in London.",
  ),
  q(
    "q-gov-7",
    ["voting-age-18"],
    "At what age can you vote in a general election?",
    "18",
    ["16", "21", "25"],
    "You can vote in a general election from the age of 18 if registered.",
    "easy",
  ),
  q(
    "q-gov-8",
    ["devolved-administrations"],
    "What is the name of the Welsh Parliament?",
    "The Senedd",
    ["The Dáil", "The Assembly of Wales Council", "The Stormont"],
    "The Welsh Parliament is called the Senedd.",
  ),
  q(
    "q-gov-9",
    ["speaker-of-commons"],
    "Who is responsible for keeping order during debates in the House of Commons?",
    "The Speaker",
    ["The Prime Minister", "The monarch", "The Lord Mayor"],
    "The Speaker chairs Commons debates and is politically neutral.",
  ),
  q(
    "q-gov-10",
    ["civil-service-neutral"],
    "Which statement about civil servants is true?",
    "They are politically neutral",
    [
      "They are elected by the public",
      "They must belong to the governing party",
      "They write the laws",
    ],
    "Civil servants are politically neutral and serve whichever party is in power.",
  ),

  // ── Law & Justice ─────────────────────────────────────────────────────
  q(
    "q-law-1",
    ["police-protect-public"],
    "What is one of the main duties of the police?",
    "To protect life and property and prevent crime",
    ["To make new laws", "To collect taxes", "To run the courts"],
    "The police protect life and property, prevent and detect crime, and keep the peace.",
  ),
  q(
    "q-law-2",
    ["judiciary-independent"],
    "What is the role of judges in the UK?",
    "To interpret and apply the law independently",
    ["To make new laws", "To lead the government", "To command the armed forces"],
    "Judges are independent of government and apply the law fairly.",
  ),
  q(
    "q-law-3",
    ["criminal-vs-civil-law"],
    "Which of these is dealt with by criminal law?",
    "Theft",
    [
      "A disagreement over a contract",
      "A dispute between neighbours over a fence",
      "An unpaid debt",
    ],
    "Criminal law covers crimes such as theft and assault; civil law settles private disputes.",
  ),
  q(
    "q-law-4",
    ["jury-system"],
    "In a serious criminal trial, who decides whether the accused is guilty?",
    "A jury of members of the public",
    ["The police", "The Prime Minister", "A single government official"],
    "A jury decides guilt in serious criminal cases.",
  ),
  q(
    "q-law-5",
    ["police-and-crime-commissioners"],
    "In England and Wales, how are Police and Crime Commissioners chosen?",
    "They are elected by the public",
    [
      "They are appointed by the monarch",
      "They are chosen by judges",
      "They inherit the role",
    ],
    "Police and Crime Commissioners are elected to oversee local policing.",
  ),

  // ── Rights & Responsibilities ─────────────────────────────────────────
  q(
    "q-rights-1",
    ["nhs-free-at-point-of-use"],
    "What does the NHS provide?",
    "Healthcare that is mostly free at the point of use",
    ["Free housing for all", "Unemployment benefits only", "Private health insurance"],
    "The National Health Service provides healthcare mostly free at the point of use.",
  ),
  q(
    "q-rights-2",
    ["paying-tax"],
    "Income tax in the UK helps to pay for:",
    "Public services such as the NHS",
    ["The monarch's personal wealth", "Private companies' profits", "Foreign governments"],
    "Tax funds public services such as the NHS, schools and roads.",
  ),
  q(
    "q-rights-3",
    ["jury-duty-responsibility"],
    "Serving on a jury when called is best described as:",
    "A responsibility of those registered to vote",
    ["An optional paid job", "A punishment for a crime", "Something only lawyers do"],
    "Jury service is a responsibility for those aged 18+ who are registered to vote.",
  ),
  q(
    "q-rights-4",
    ["national-insurance"],
    "National Insurance contributions help to pay for:",
    "Benefits and the State Pension",
    ["Television channels", "Private school fees", "Local newspapers"],
    "Most workers pay National Insurance, which helps fund benefits and the State Pension.",
  ),
  q(
    "q-rights-5",
    ["respecting-environment"],
    "Which of these is a way of looking after the environment?",
    "Recycling and not dropping litter",
    [
      "Leaving lights on at all times",
      "Pouring oil into rivers",
      "Burning rubbish in the street",
    ],
    "Caring for the environment, such as recycling, is a shared responsibility.",
    "easy",
  ),

  // ── Culture & Traditions ──────────────────────────────────────────────
  q(
    "q-culture-1",
    ["remembrance-day"],
    "What do people wear to mark Remembrance Day on 11 November?",
    "A poppy",
    ["A daffodil", "A shamrock", "A red rose"],
    "People wear poppies on Remembrance Day to remember those who died in wars.",
  ),
  q(
    "q-culture-2",
    ["bonfire-night"],
    "What event does Bonfire Night on 5 November commemorate?",
    "The failure of the Gunpowder Plot of 1605",
    [
      "The end of the Second World War",
      "The Great Fire of London",
      "The signing of Magna Carta",
    ],
    "Bonfire Night marks the failed Gunpowder Plot of 1605.",
  ),
  q(
    "q-culture-3",
    ["christmas-day"],
    "On what date is Christmas Day celebrated?",
    "25 December",
    ["1 January", "31 October", "26 December"],
    "Christmas Day is on 25 December.",
    "easy",
  ),
  q(
    "q-culture-4",
    ["easter-tradition"],
    "Easter is a Christian festival that marks:",
    "The death and resurrection of Jesus Christ",
    ["The birth of Jesus Christ", "The new harvest", "The new year"],
    "Easter marks the death and resurrection of Jesus Christ.",
  ),
  q(
    "q-culture-5",
    ["hogmanay-scotland"],
    "Hogmanay is the traditional celebration of which occasion in Scotland?",
    "New Year's Eve",
    ["Christmas", "Midsummer", "Harvest"],
    "Hogmanay is the Scottish celebration of New Year's Eve.",
  ),
  q(
    "q-culture-6",
    ["diwali-celebration"],
    "Diwali, the festival of lights, is celebrated by:",
    "Hindus and Sikhs",
    ["Only Christians", "Only Muslims", "No religious groups"],
    "Diwali is celebrated by Hindus and Sikhs in the autumn.",
  ),

  // ── Geography & Symbols ───────────────────────────────────────────────
  q(
    "q-geo-1",
    ["st-george-england"],
    "Who is the patron saint of England?",
    "St George",
    ["St Andrew", "St David", "St Patrick"],
    "St George is the patron saint of England.",
    "easy",
  ),
  q(
    "q-geo-2",
    ["st-andrew-scotland"],
    "St Andrew is the patron saint of which country?",
    "Scotland",
    ["Wales", "England", "Northern Ireland"],
    "St Andrew is the patron saint of Scotland.",
  ),
  q(
    "q-geo-3",
    ["st-david-wales"],
    "Which patron saint is associated with Wales?",
    "St David",
    ["St George", "St Patrick", "St Andrew"],
    "St David is the patron saint of Wales.",
  ),
  q(
    "q-geo-4",
    ["st-patrick-northern-ireland"],
    "St Patrick is the patron saint of:",
    "Northern Ireland",
    ["Scotland", "England", "Wales"],
    "St Patrick is the patron saint of Northern Ireland.",
  ),
  q(
    "q-geo-5",
    ["ben-nevis-highest"],
    "What is the highest mountain in the United Kingdom?",
    "Ben Nevis",
    ["Snowdon", "Scafell Pike", "Helvellyn"],
    "Ben Nevis in Scotland is the highest mountain in the UK.",
  ),
  q(
    "q-geo-6",
    ["national-flowers"],
    "Which flower is the national symbol of Scotland?",
    "The thistle",
    ["The rose", "The daffodil", "The shamrock"],
    "The thistle is Scotland's national flower; the rose is England's.",
  ),
  q(
    "q-geo-7",
    ["national-flowers"],
    "The daffodil is associated with which part of the UK?",
    "Wales",
    ["England", "Scotland", "Northern Ireland"],
    "The daffodil is a national symbol of Wales.",
  ),
  q(
    "q-geo-8",
    ["big-ben-clock"],
    "'Big Ben' is the nickname of:",
    "The great bell in the clock tower at the Houses of Parliament",
    ["A famous London bridge", "The London Underground", "A royal palace"],
    "Big Ben is the great bell of the clock at the Houses of Parliament.",
  ),

  // ── Sport, Arts & Science ─────────────────────────────────────────────
  q(
    "q-sci-1",
    ["bannister-four-minute-mile"],
    "Who was the first person to run a mile in under four minutes?",
    "Sir Roger Bannister",
    ["Sir Steve Redgrave", "Sir Mo Farah", "Sir Chris Hoy"],
    "Sir Roger Bannister ran the first sub-four-minute mile in 1954.",
  ),
  q(
    "q-sci-2",
    ["bannister-four-minute-mile"],
    "Sir Roger Bannister is famous in which sport?",
    "Athletics (running)",
    ["Cycling", "Rowing", "Swimming"],
    "Roger Bannister was a runner, famous for the four-minute mile.",
  ),
  q(
    "q-sci-3",
    ["shakespeare-playwright"],
    "Which famous playwright came from Stratford-upon-Avon?",
    "William Shakespeare",
    ["Charles Dickens", "Geoffrey Chaucer", "Robert Burns"],
    "William Shakespeare, the playwright, was born in Stratford-upon-Avon.",
  ),
  q(
    "q-sci-4",
    ["shakespeare-playwright"],
    "'Hamlet' and 'Romeo and Juliet' were written by:",
    "William Shakespeare",
    ["Jane Austen", "William Wordsworth", "Thomas Hardy"],
    "These plays were written by William Shakespeare.",
  ),
  q(
    "q-sci-5",
    ["newton-gravity"],
    "Sir Isaac Newton is best known for his work on:",
    "Gravity and the laws of motion",
    [
      "The theory of evolution",
      "The discovery of penicillin",
      "The invention of the telephone",
    ],
    "Isaac Newton is famous for his work on gravity and motion.",
  ),
  q(
    "q-sci-6",
    ["darwin-evolution"],
    "Who developed the theory of evolution?",
    "Charles Darwin",
    ["Isaac Newton", "Alexander Fleming", "Michael Faraday"],
    "Charles Darwin developed the theory of evolution and wrote 'On the Origin of Species'.",
  ),
  q(
    "q-sci-7",
    ["fleming-penicillin"],
    "What did Sir Alexander Fleming discover?",
    "Penicillin",
    ["The structure of DNA", "Radioactivity", "The steam engine"],
    "Alexander Fleming discovered penicillin, the first widely used antibiotic.",
  ),
  q(
    "q-sci-8",
    ["turing-computing"],
    "Alan Turing is remembered as a founder of:",
    "Modern computing",
    ["Modern medicine", "Modern chemistry", "Modern astronomy"],
    "Alan Turing helped break wartime codes and is seen as a founder of computing.",
  ),
  q(
    "q-sci-9",
    ["wimbledon-tennis"],
    "Wimbledon is a world-famous tournament in which sport?",
    "Tennis",
    ["Golf", "Cricket", "Rugby"],
    "Wimbledon is the oldest tennis tournament in the world.",
  ),
  q(
    "q-sci-10",
    ["the-beatles"],
    "The Beatles, one of the most influential 1960s pop groups, came from which city?",
    "Liverpool",
    ["Manchester", "London", "Birmingham"],
    "The Beatles were from Liverpool.",
  ),
  q(
    "q-sci-11",
    ["turner-painter"],
    "The Turner Prize for art is named after which British painter?",
    "JMW Turner",
    ["John Constable", "David Hockney", "Henry Moore"],
    "The Turner Prize is named after the landscape painter JMW Turner.",
  ),
  q(
    "q-sci-12",
    ["football-origins"],
    "Which sport is the most popular in the UK and had its first professional clubs formed in Britain?",
    "Football",
    ["Basketball", "Baseball", "Ice hockey"],
    "Football is the UK's most popular sport, with the first professional clubs formed in Britain.",
    "easy",
  ),

  // ── Batch 2: broader coverage and extra variants ──────────────────────
  q(
    "q-history-17",
    ["romans-in-britain"],
    "Which ancient power built Hadrian's Wall and ruled Britain for around 400 years?",
    "The Romans",
    ["The Vikings", "The Normans", "The Saxons"],
    "The Romans ruled Britain for about 400 years and built Hadrian's Wall.",
  ),
  q(
    "q-history-18",
    ["boudicca-revolt"],
    "Boudicca is remembered for leading a revolt against which rulers?",
    "The Romans",
    ["The Normans", "The French", "The Spanish"],
    "Boudicca led a British tribe in revolt against the Roman army.",
  ),
  q(
    "q-history-19",
    ["florence-nightingale"],
    "Florence Nightingale is regarded as the founder of modern:",
    "Nursing",
    ["Surgery", "Dentistry", "Pharmacy"],
    "Florence Nightingale founded modern nursing during the Crimean War.",
  ),
  q(
    "q-history-20",
    ["abolition-slave-trade"],
    "Who was a leading campaigner for the abolition of the slave trade?",
    "William Wilberforce",
    ["William the Conqueror", "Winston Churchill", "William Shakespeare"],
    "William Wilberforce campaigned against the slave trade, made illegal in 1807.",
  ),
  q(
    "q-history-21",
    ["nhs-founded-1948"],
    "In which year was the National Health Service (NHS) founded?",
    "1948",
    ["1918", "1928", "1972"],
    "The NHS was founded in 1948 to provide healthcare for everyone.",
  ),
  q(
    "q-history-22",
    ["nhs-founded-1948"],
    "Which Health Minister led the creation of the NHS in 1948?",
    "Aneurin Bevan",
    ["Winston Churchill", "Margaret Thatcher", "Clement Attlee"],
    "Aneurin Bevan, as Minister of Health, led the creation of the NHS in 1948 — under Clement Attlee's government.",
    "hard",
  ),
  q(
    "q-history-23",
    ["stonehenge-builders"],
    "Stonehenge, one of the most famous prehistoric monuments, is located in:",
    "Wiltshire, England",
    ["the Scottish Highlands", "North Wales", "County Antrim"],
    "Stonehenge stands in Wiltshire and dates from the Stone and Bronze Ages.",
  ),
  q(
    "q-history-24",
    ["great-fire-1666"],
    "The Great Fire of London happened in which year?",
    "1666",
    ["1066", "1605", "1750"],
    "The Great Fire of London destroyed much of the city in 1666.",
  ),
  q(
    "q-society-7",
    ["queen-elizabeth-ii-reign"],
    "Queen Elizabeth II is notable for being:",
    "The longest-reigning monarch in British history",
    [
      "The first British queen",
      "An elected head of government",
      "The head of the United Nations",
    ],
    "Elizabeth II reigned from 1952 until 2022, longer than any previous monarch.",
  ),
  q(
    "q-society-8",
    ["patron-saints-days"],
    "Which patron saint's day is celebrated on 30 November?",
    "St Andrew's Day",
    ["St George's Day", "St David's Day", "St Patrick's Day"],
    "St Andrew's Day (Scotland) falls on 30 November.",
  ),
  q(
    "q-society-9",
    ["patron-saints-days"],
    "St Patrick's Day is celebrated on which date?",
    "17 March",
    ["1 March", "23 April", "30 November"],
    "St Patrick's Day is on 17 March.",
  ),
  q(
    "q-gov-11",
    ["commonwealth-association"],
    "The Commonwealth is an association of countries that were mostly once part of:",
    "The British Empire",
    ["The Roman Empire", "The European Union", "The United Nations"],
    "The Commonwealth links countries, most formerly part of the British Empire.",
  ),
  q(
    "q-gov-12",
    ["house-of-lords-unelected"],
    "Which statement about the House of Lords is correct?",
    "Its members are not elected by the public",
    [
      "Its members are elected every five years",
      "It has more power than the Commons",
      "It chooses the Prime Minister",
    ],
    "Members of the House of Lords are not elected; they review laws from the Commons.",
  ),
  q(
    "q-gov-13",
    ["secret-ballot"],
    "How do people cast their vote in UK elections?",
    "In secret",
    [
      "By a public show of hands",
      "By telling a police officer",
      "Only in writing to an MP",
    ],
    "Voting is by secret ballot, so no one can be forced to reveal their choice.",
  ),
  q(
    "q-gov-14",
    ["constitutional-monarchy"],
    "In the UK's constitutional monarchy, who makes the important political decisions?",
    "The elected government",
    ["The monarch alone", "The House of Lords alone", "The armed forces"],
    "The monarch is head of state, but political decisions are made by the elected government.",
  ),
  q(
    "q-gov-15",
    ["mps-elected"],
    "What does 'MP' stand for?",
    "Member of Parliament",
    ["Minister of Police", "Master of Protocol", "Member of the Press"],
    "MP stands for Member of Parliament.",
    "easy",
  ),
  q(
    "q-law-6",
    ["magistrates-courts"],
    "In England and Wales, most minor criminal cases are heard by:",
    "Magistrates",
    ["The House of Lords", "Police officers", "Government ministers"],
    "Magistrates, usually unpaid local volunteers, hear most minor criminal cases.",
  ),
  q(
    "q-law-7",
    ["judiciary-independent"],
    "Judges in the UK are independent of:",
    "The government",
    ["The law", "The public entirely", "All courts"],
    "Judges are independent of government so they can apply the law fairly.",
  ),
  q(
    "q-rights-6",
    ["human-rights-equality"],
    "It is against the law to discriminate against someone because of their:",
    "Race, religion, sex, age or disability",
    ["Choice of football team", "Favourite food", "Taste in music"],
    "Discrimination on grounds such as race, religion, sex, age or disability is unlawful.",
  ),
  q(
    "q-rights-7",
    ["freedom-of-speech"],
    "Freedom of speech in the UK allows people to express views, provided they:",
    "Stay within the law and do not incite hatred",
    ["Only speak about politics", "Have permission from an MP", "Pay a special fee"],
    "Freedom of speech is protected, but it must stay within the law.",
  ),
  q(
    "q-rights-8",
    ["right-to-vote"],
    "Registering to vote is best described as:",
    "A civic responsibility and a right",
    ["A criminal offence", "Something only MPs do", "A way to avoid tax"],
    "Voting is a right, and registering to vote is a civic responsibility.",
  ),
  q(
    "q-culture-7",
    ["valentines-day"],
    "On 14 February, people who are in love traditionally:",
    "Send cards and gifts to one another",
    ["Light bonfires", "Wear poppies", "Carve pumpkins"],
    "St Valentine's Day on 14 February is for sending cards and gifts to loved ones.",
  ),
  q(
    "q-culture-8",
    ["mothering-sunday"],
    "Mother's Day in the UK falls on:",
    "The Sunday three weeks before Easter",
    ["The first Sunday in June", "25 December", "The last Sunday in November"],
    "Mothering Sunday is three weeks before Easter.",
    "hard",
  ),
  q(
    "q-culture-9",
    ["edinburgh-festival"],
    "The Edinburgh Festival, famous for its Fringe, is held in which season?",
    "Summer",
    ["Winter", "Early spring", "Late autumn"],
    "The Edinburgh Festival takes place each summer in Scotland's capital.",
  ),
  q(
    "q-culture-10",
    ["remembrance-day"],
    "Remembrance Day is held on which date each year?",
    "11 November",
    ["5 November", "1 March", "25 December"],
    "Remembrance Day is on 11 November.",
  ),
  q(
    "q-geo-9",
    ["severn-longest-river"],
    "What is the longest river in the United Kingdom?",
    "The River Severn",
    ["The River Thames", "The River Mersey", "The River Clyde"],
    "The River Severn is the longest river in the UK.",
  ),
  q(
    "q-geo-10",
    ["snowdon-wales"],
    "Snowdon, the highest mountain in Wales, gives its name to which national park?",
    "Snowdonia",
    ["The Lake District", "The Peak District", "the Cairngorms"],
    "Snowdon lies within the Snowdonia national park in Wales.",
  ),
  q(
    "q-geo-11",
    ["lake-district"],
    "The Lake District, the UK's largest national park, is found in:",
    "North-west England",
    ["Southern Scotland", "West Wales", "Eastern Northern Ireland"],
    "The Lake District is in north-west England.",
  ),
  q(
    "q-geo-12",
    ["national-flowers"],
    "The shamrock is a national symbol of:",
    "Northern Ireland",
    ["England", "Scotland", "Wales"],
    "The shamrock is associated with Northern Ireland; the rose with England.",
  ),
  q(
    "q-geo-13",
    ["st-george-england"],
    "The flag of England shows which design?",
    "A red cross on a white background",
    [
      "A white diagonal cross on blue",
      "A red dragon on green and white",
      "A harp on a blue background",
    ],
    "St George's Cross — a red cross on white — is the flag of England.",
  ),
  q(
    "q-sci-13",
    ["dickens-novelist"],
    "Who wrote the novels 'Oliver Twist' and 'A Christmas Carol'?",
    "Charles Dickens",
    ["William Shakespeare", "Charles Darwin", "Rudyard Kipling"],
    "Charles Dickens was a famous 19th-century novelist.",
  ),
  q(
    "q-sci-14",
    ["darwin-evolution"],
    "Which book did Charles Darwin write?",
    "On the Origin of Species",
    ["A Christmas Carol", "Principia Mathematica", "Hamlet"],
    "Darwin set out his theory of evolution in 'On the Origin of Species'.",
    "hard",
  ),
  q(
    "q-sci-15",
    ["fleming-penicillin"],
    "Sir Alexander Fleming, who discovered penicillin, was from which UK nation?",
    "Scotland",
    ["Wales", "England", "Northern Ireland"],
    "Alexander Fleming was a Scottish scientist.",
    "hard",
  ),
  q(
    "q-sci-16",
    ["newton-gravity"],
    "Which famous scientist described the laws of motion?",
    "Sir Isaac Newton",
    ["Charles Darwin", "Alan Turing", "Michael Faraday"],
    "Isaac Newton is famous for the laws of motion and his work on gravity.",
  ),

  // ── Batch 3: depth for lighter categories ─────────────────────────────
  q(
    "q-values-7",
    ["fundamental-principles"],
    "Which of these is NOT one of the fundamental principles of British life?",
    "Loyalty to a single political party",
    ["Democracy", "Individual liberty", "The rule of law"],
    "Democracy, the rule of law, individual liberty and tolerance are the principles — not party loyalty.",
  ),
  q(
    "q-values-8",
    ["resident-responsibilities"],
    "Looking after the area you live in and the environment is:",
    "A responsibility residents agree to accept",
    ["Only the council's job", "Required only of homeowners", "Not expected of anyone"],
    "Caring for your local area and the environment is one of the agreed responsibilities.",
  ),
  q(
    "q-values-9",
    ["tolerance-and-extremism"],
    "British society expects people to show tolerance, but it does not accept:",
    "Extremism and intolerance",
    ["Different religions", "Different opinions", "Peaceful protest"],
    "Tolerance is valued; extremism and intolerance are not accepted.",
  ),
  q(
    "q-values-10",
    ["english-language-requirement"],
    "Applicants for citizenship are normally expected to be able to:",
    "Speak and read English to a required standard",
    ["Speak three languages", "Pass a driving test", "Own property in the UK"],
    "A required standard of English is normally expected for citizenship.",
  ),
  q(
    "q-values-11",
    ["everyone-equal-under-law"],
    "The idea that no one is above the law is part of which principle?",
    "The rule of law",
    ["Free trade", "Constitutional monarchy", "Devolution"],
    "Equality before the law is central to the rule of law.",
  ),
  q(
    "q-uk-9",
    ["capital-cities"],
    "What is the capital city of the United Kingdom?",
    "London",
    ["Birmingham", "Manchester", "Edinburgh"],
    "London is the capital of the UK.",
    "easy",
  ),
  q(
    "q-uk-10",
    ["union-flag-name"],
    "The Union Flag combines the crosses of which three patron saints?",
    "St George, St Andrew and St Patrick",
    [
      "St George, St David and St Patrick",
      "St Andrew, St David and St George",
      "St David, St Patrick and St Andrew",
    ],
    "The Union Flag combines the crosses of St George, St Andrew and St Patrick.",
    "hard",
  ),
  q(
    "q-uk-11",
    ["overseas-territories"],
    "Which of these is a British overseas territory?",
    "The Falkland Islands",
    ["The Isle of Man", "Jersey", "Guernsey"],
    "The Falkland Islands are an overseas territory; the others are Crown dependencies.",
    "hard",
  ),
  q(
    "q-uk-12",
    ["great-britain-definition"],
    "Which country is part of the UK but NOT part of Great Britain?",
    "Northern Ireland",
    ["Scotland", "Wales", "England"],
    "Great Britain is England, Scotland and Wales; Northern Ireland is part of the UK but not GB.",
  ),
  q(
    "q-society-10",
    ["currency-pound"],
    "How many pence make up one pound sterling?",
    "100",
    ["50", "10", "1000"],
    "The pound is divided into 100 pence.",
  ),
  q(
    "q-society-11",
    ["church-of-england-established"],
    "The established church in England is the:",
    "Church of England",
    ["Roman Catholic Church", "Church of Scotland", "Methodist Church"],
    "The Church of England is the established church, with the monarch as its head.",
  ),
  q(
    "q-society-12",
    ["uk-population-growth"],
    "Which of these has contributed to the growth of the UK population?",
    "Migration",
    ["A fall in life expectancy", "The end of the NHS", "Leaving the Commonwealth"],
    "Population growth has been driven partly by migration.",
  ),
  q(
    "q-society-13",
    ["queen-elizabeth-ii-reign"],
    "In which year did Queen Elizabeth II begin her reign?",
    "1952",
    ["1945", "1936", "1969"],
    "Elizabeth II's reign began in 1952.",
    "hard",
  ),
  q(
    "q-law-8",
    ["police-protect-public"],
    "Which of these must the police themselves do?",
    "Obey the law",
    ["Make new laws", "Choose judges", "Collect income tax"],
    "The police must obey the law while protecting the public and preventing crime.",
  ),
  q(
    "q-law-9",
    ["criminal-vs-civil-law"],
    "A dispute between two people over an unpaid debt would usually be dealt with by:",
    "Civil law",
    ["Criminal law", "Military law", "Church law"],
    "Civil law settles disputes between people or organisations; criminal law covers crimes.",
  ),
  q(
    "q-law-10",
    ["legal-aid"],
    "People who cannot afford legal help may be able to get:",
    "Free or low-cost advice, and sometimes legal aid",
    ["A guaranteed not-guilty verdict", "A seat in Parliament", "Exemption from all laws"],
    "Those who cannot afford it may get free advice or legal aid.",
  ),
  q(
    "q-law-11",
    ["jury-system"],
    "Roughly how is a jury made up?",
    "From members of the public",
    ["From police officers", "From government ministers", "From qualified lawyers only"],
    "A jury is made up of members of the public.",
  ),
  q(
    "q-law-12",
    ["judiciary-independent"],
    "Why is it important that judges are independent?",
    "So they can apply the law fairly, free from political pressure",
    ["So they can make new laws", "So they can run elections", "So they can set tax rates"],
    "Judicial independence means the law is applied fairly, free of government interference.",
  ),
  q(
    "q-rights-9",
    ["nhs-free-at-point-of-use"],
    "Care from the NHS is mostly:",
    "Free at the point of use",
    [
      "Paid for in cash each visit",
      "Only for citizens born in the UK",
      "Available only privately",
    ],
    "NHS care is mostly free at the point of use for UK residents.",
  ),
  q(
    "q-rights-10",
    ["human-rights-equality"],
    "Treating someone unfairly because of their disability is:",
    "Against the law",
    ["Allowed at work", "Required by employers", "Only a moral matter, not legal"],
    "Discrimination because of disability — or race, sex, religion, age — is unlawful.",
  ),
  q(
    "q-rights-11",
    ["paying-tax"],
    "Most people in the UK pay income tax on their:",
    "Earnings",
    ["Holidays abroad", "Number of children", "Hobbies"],
    "Income tax is paid on earnings and helps fund public services.",
  ),
  q(
    "q-rights-12",
    ["jury-duty-responsibility"],
    "From what age can a person be called for jury service?",
    "18",
    ["16", "21", "30"],
    "Those aged 18 or over who are registered to vote may be called for jury service.",
  ),
  q(
    "q-rights-13",
    ["freedom-of-speech"],
    "Freedom of speech does NOT protect speech that:",
    "Incites hatred or breaks the law",
    ["Criticises the government", "Discusses religion", "Expresses an unpopular opinion"],
    "Free speech is protected unless it incites hatred or otherwise breaks the law.",
  ),
  q(
    "q-gov-16",
    ["voting-age-18"],
    "To vote in a general election you must be 18 and:",
    "Registered to vote",
    ["A member of a political party", "A homeowner", "Born in the UK"],
    "You must be 18 and registered to vote.",
  ),
  q(
    "q-gov-17",
    ["devolved-administrations"],
    "Which body holds devolved powers in Northern Ireland?",
    "The Northern Ireland Assembly",
    ["The Senedd", "The Scottish Parliament", "The House of Lords"],
    "Devolved powers in Northern Ireland sit with the Northern Ireland Assembly.",
  ),
  q(
    "q-history-25",
    ["world-war-one"],
    "In which year did the First World War end?",
    "1918",
    ["1914", "1945", "1939"],
    "The First World War ended in 1918.",
  ),
  q(
    "q-history-26",
    ["act-of-union-1707"],
    "The Kingdom of Great Britain was created by the Act of Union in:",
    "1707",
    ["1066", "1215", "1801"],
    "The 1707 Act of Union joined England and Scotland as Great Britain.",
    "hard",
  ),
  q(
    "q-culture-11",
    ["christmas-day"],
    "Which of these is a public holiday celebrated by Christians as the birth of Jesus?",
    "Christmas Day",
    ["Bonfire Night", "Hogmanay", "Diwali"],
    "Christmas Day, 25 December, marks the birth of Jesus Christ.",
  ),
  q(
    "q-culture-12",
    ["bank-holidays"],
    "What are 'bank holidays'?",
    "Public holidays when most businesses close",
    [
      "Days when banks charge no fees",
      "Religious fasting days",
      "Days only banks are open",
    ],
    "Bank holidays are public holidays when most businesses and many shops close.",
  ),
  q(
    "q-culture-13",
    ["easter-tradition"],
    "Good Friday and Easter Monday are:",
    "Public holidays around Easter",
    ["Days in the summer holidays", "Parts of the Christmas period", "Election days"],
    "Good Friday and Easter Monday are public holidays around Easter.",
  ),
  q(
    "q-geo-14",
    ["ben-nevis-highest"],
    "Ben Nevis, the UK's highest mountain, is located in:",
    "Scotland",
    ["Wales", "England", "Northern Ireland"],
    "Ben Nevis is in Scotland.",
  ),
  q(
    "q-geo-15",
    ["national-flowers"],
    "Which flower is the national symbol of England?",
    "The rose",
    ["The thistle", "The daffodil", "The shamrock"],
    "The rose is England's national flower.",
  ),
  q(
    "q-geo-16",
    ["big-ben-clock"],
    "The clock tower nicknamed 'Big Ben' is found at:",
    "The Houses of Parliament in London",
    ["Edinburgh Castle", "Cardiff Bay", "Windsor Castle"],
    "Big Ben is the bell in the clock tower at the Houses of Parliament.",
  ),
  q(
    "q-sci-17",
    ["turing-computing"],
    "During the Second World War, Alan Turing was known for:",
    "Helping to break enemy codes",
    ["Commanding the navy", "Designing fighter planes", "Leading the government"],
    "Turing helped break enemy codes and is seen as a founder of computing.",
  ),
  q(
    "q-sci-18",
    ["wimbledon-tennis"],
    "Wimbledon, held in London each year, is the oldest tournament in which sport?",
    "Tennis",
    ["Golf", "Rowing", "Athletics"],
    "Wimbledon is the world's oldest tennis tournament.",
  ),
  q(
    "q-sci-19",
    ["shakespeare-playwright"],
    "William Shakespeare is best described as a:",
    "Playwright and poet",
    ["Scientist", "Composer", "Explorer"],
    "Shakespeare was a playwright and poet.",
    "easy",
  ),
];

export const questionById = new Map(questions.map((q) => [q.id, q]));

export const questionsForCategory = (categoryId: string) =>
  questions.filter((q) => q.categoryId === categoryId);
